### PR TITLE
Refactor and cleanup

### PR DESCRIPTION
**Pull request by Roboe**
## Work done

* Clean code
* Improve implementation of #5: overlays are creating dynamically (`arr.reduce()`) depending on the state
* Improve implementation of #6 too with `arr.filter()` and `getQueries()` 

## Demos

* Show **all** layers by default: https://roboe.github.io/fprsmap/
* Show a **single** layer (Fairphoners Groups): https://roboe.github.io/fprsmap/?show=communities
* Show **multiple** layers (meetups and shops): https://roboe.github.io/fprsmap/?show=shops,meetups
* **Avoid errors** and name duplicities (load Fairphoners with URI garbage): https://roboe.github.io/fprsmap/?show=communities,gar,ba,ge,communities

## Dilemma

Should we keep calling Fairphoners Groups `communities` or `groups`? I've implemented #6 with `communities`, but I can easily change it (just replacing it in [line 42](https://github.com/newluck77/fprsmap/pull/13/files#diff-9bc4cbda5c59e3242b793ba6906bd591R42)) for `groups` or anything **before** you merge this PR.

## Pros an cons

Pros of this implementation (every one needs actual implementation, and a new issue):
* We can further automatize the JSON collection for every layer just specifying an `endpoint` String property on the state (yay!)
* We can control which layers to show by default just adding a `showByDefault` boolean property to the state

### CODE REVIEW

**Comment by newluck77** [comment]
> Should we keep calling Fairphoners Groups communities or groups?

I think this will become obsolete anyway because we have two different layers now, one for angels and one for meetups.

I'd implement it like this: If((meetup.startdate - today) <  2months): show marker; 
Pro would be that only active communities (aka meetups) will show up in the map. We could remove the layer communities/groups altogether.

**Comment by Roboe** [comment]
> only active communities (aka meetups) will show up in the map

I think you haven't considered the case when a community is not active but some people discover it thorugh the map and the thing start to move again... maybe is better a marker color indicator? Green for active, amber for not-so-active...

**Comment by newluck77** [comment]
Fair enough! This could be a simple boolean `hasMeetupInNextTwoMonths` 
provided by the endpoint database. We should draw up some specification 
for the database with the info we need...


Am 11.09.2016 um 13:25 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
I've set up directories as we talked in #15. What do you think?

**Comment by newluck77** [comment]
I took me over an hour to understand all the new functions (especially .reduce()). But when I noticed that different queries can actually create different properties of an object, it was mind-blowing!!!

##Remarks
Instead of calling the array ´groups´ in [line 37](https://github.com/newluck77/fprsmap/pull/13/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR37), we should rather call it ´layers´ as it represents [one geographic dataset](http://support.esri.com/other-resources/gis-dictionary/term/layer). 
Generally the naming of some variables and functions is a bit confusing to me (getMapOverlays vs getMapLayers for example).

##Bugs
- One thing doesn't work for me: https://roboe.github.io/fprsmap/?show=angel should produce default, but instead nothing is displayed.
- The getMapOverlays(...) function in [line 57](https://github.com/newluck77/fprsmap/pull/13/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR57) expects 2 objects, but you only hand it one in [line 92](https://github.com/newluck77/fprsmap/pull/13/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR92). I'm not sure if this is a mistake or only my lacking knowledge of JS... ;)

**Comment by Roboe** [comment]
> to understand all the new functions (especially .reduce()) [...] it was mind-blowing!!!

Those functions (`map()`, `filter()` and `reduce()`) are idiomatic JavaScript, and are basic for manipulating data. You can have a single source of data (the state) and avoid a lot of `for`s (business logic), as my friend @soyguijarro majestically explains in [these slides](http://slides.com/soyguijarro/declarative-looping#/) (warning: tempting ES2015 syntax inside!).

> Instead of calling the array `groups` in line 37, we should rather call it `layers`

Ok, I'm fine with that, :+1: 
Your semantics arguments are sharp: I had a hard time trying to be coherent with the Leaflet docs (a [layer](http://leafletjs.com/reference.html#control-layers-addbaselayer) and an [overlay](http://leafletjs.com/reference.html#control-layers-addoverlay) are not the same) and English semantics. What alternatives do you suggest for `getMapOverlays()` and `getMapLayers()`?

> `?show=not-a-layer` should produce `default`

Oops. That case wasn't taken into account. Will look at it now, :)

> getMapOverlays(...) function in line 57 expects 2 objects

JavaScript's functions signatures can accept as many arguments as you want, or even less than declared. In this case, the second argument is optional. If you see the [62nd line](https://github.com/newluck77/fprsmap/pull/13/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR62), you could observe that, if the `defaultOverlays` is [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy), then the value `{}` (empty object) will be used.

**Comment by newluck77** [comment]
What alternatives do you suggest for `getMapOverlays() `and `getMapLayers()`?

Hmmm. We should probably differ between `Overlays `and `BaseLayers`. Both of them are layers, so `getMapLayers()` is correct.

**Comment by Roboe** [comment]
Ok, think we can merge this PR because it's gaining complexity and we are already implementing things on top of this work.
So I'll open issues for every unimplemented topic we've talked here, take away the `[WIP]` tag and then you could transfer the repo to the @WeAreFairphone organization.

**Comment by Roboe** [comment]
Go ahead! Merge it and transfer the repo, @StefanBrand, :+1:

**Pull request merged**
